# Generated by Django 4.1.5 on 2023-01-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_files', '0002_demand_geography_main_navigation_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='thierd_menu',
            new_name='third_menu',
        ),
    ]
